name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Unraid Integration
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thanks for suggesting a new feature! Your ideas help make this integration better.

        **Before submitting**, please:
        - Search existing [open](https://github.com/ruaan-deysel/ha-unraid/issues) and [closed](https://github.com/ruaan-deysel/ha-unraid/issues?q=is%3Aissue+is%3Aclosed) issues
        - Check if the feature is available in Unraid's GraphQL API (required for implementation)
        - Consider if this aligns with Home Assistant integration standards

  - type: dropdown
    id: feature_category
    attributes:
      label: 📂 Feature Category
      description: "What area of the integration does this feature relate to?"
      options:
        - "System Monitoring - CPU, RAM, temperatures, uptime"
        - "Storage Monitoring - Array status, disk health, SMART data"
        - "Docker Management - Container controls, status, updates"
        - "VM Management - Virtual machine controls and monitoring"
        - "UPS Monitoring - Battery status, power metrics"
        - "Notifications - Unraid alerts and warnings in HA"
        - "Network Monitoring - Network interfaces, bandwidth"
        - "Shares - User share monitoring and management"
        - "Parity Operations - Parity check status and controls"
        - "Configuration - Setup, options, polling intervals"
        - "Services - Service management (array start/stop, etc.)"
        - "Other - Something not listed above"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 🎯 Use Case / Problem Solved
      description: "What problem does this feature solve? How would you use it?"
      placeholder: |
        **Problem:**
        Currently I can only see if a parity check is running, but not how much progress has been made.

        **Use Case:**
        I want to create an automation that sends notifications when parity check reaches 50% and 90% completion.

        **Benefit:**
        This would help users better monitor and plan around long-running maintenance operations.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 💡 Proposed Solution
      description: "How do you think this feature should work?"
      placeholder: |
        **Implementation idea:**
        - Add a new sensor entity: `sensor.unraid_parity_check_progress`
        - Query parity check status from Unraid GraphQL API
        - Update based on storage polling interval

        **UI/UX:**
        - Show progress percentage in entity state
        - Include estimated time remaining as an attribute
        - Add to device diagnostics
      render: markdown
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: "Have you considered any alternative solutions or workarounds?"
      placeholder: |
        **Current workarounds:**
        - Manually checking Unraid web interface
        - Using external monitoring tools

        **Why they're not ideal:**
        - Requires manual checking
        - Not integrated with Home Assistant automations
      render: markdown
    validations:
      required: false

  - type: textarea
    id: unraid_context
    attributes:
      label: 🖥️ Unraid Context
      description: "Relevant information about your Unraid setup"
      placeholder: |
        - Unraid version: 7.2.0
        - Array size: 8 drives
        - Number of Docker containers: 25
        - Number of VMs: 3
        - Specific hardware or configuration that might be relevant
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: "How important is this feature to you?"
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my experience"
        - "High - Significantly impacts usability"
        - "Critical - Blocking important use cases"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: "Would you be willing to help implement this feature?"
      options:
        - label: "I'm willing to test development versions"
        - label: "I can help with documentation"
        - label: "I have programming skills and could contribute code"
        - label: "I can provide detailed requirements and feedback"

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Additional Context
      description: "Any other relevant information, mockups, or examples"
      placeholder: |
        - Screenshots or mockups of desired UI
        - Examples from other integrations
        - Technical considerations
        - Related feature requests
        - GraphQL API fields that could be used (if known)
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: "Please confirm you have done the following:"
      options:
        - label: "I have searched existing [open](https://github.com/ruaan-deysel/ha-unraid/issues) and [closed](https://github.com/ruaan-deysel/ha-unraid/issues?q=is%3Aissue+is%3Aclosed) issues to ensure this isn't a duplicate"
          required: true
        - label: "I have clearly described the problem this feature would solve"
          required: true
        - label: "I understand that feature requests might take time or not be implemented if they are not within project scope"
          required: true
