name: 🔌 Hardware Detection Issue
description: Report missing or incorrect hardware detection (CPU, GPU, sensors, etc.)
title: "[Hardware]: "
labels: ["hardware", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🔌 Hardware Detection Issue

        This form is for reporting issues where specific hardware isn't being detected or monitored correctly.

        **Note**: Hardware detection relies on what data the Unraid GraphQL API exposes. Some hardware sensors may not be available through the API.

        **Before submitting**, please:
        - Verify the hardware appears in Unraid's web UI
        - Check if the data is available in Unraid's GraphQL API (accessible at `https://your-unraid/graphql`)
        - Ensure you're running Unraid 7.2.0 or later

  - type: textarea
    id: hardware_description
    attributes:
      label: 🔌 Hardware Description
      description: "What hardware is not being detected or monitored correctly?"
      placeholder: |
        **Hardware affected:**
        - CPU temperature sensors
        - GPU temperature and usage
        - Motherboard fan speeds
        
        **What is currently detected:**
        - Only basic CPU information
        - No temperature sensors
        - No GPU monitoring
      render: markdown
    validations:
      required: true

  - type: input
    id: unraid_version
    attributes:
      label: 🖥️ Unraid Version
      description: "Your Unraid server version (must be 7.2.0+)"
      placeholder: "7.2.0"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: 📦 Integration Version
      description: "Version of the Unraid Integration (check in HACS or manifest.json)"
      placeholder: "2025.12.0"
    validations:
      required: true

  - type: textarea
    id: system_specifications
    attributes:
      label: 💻 System Specifications
      description: "Detailed system information"
      placeholder: |
        **Motherboard:** ASUS ROG Strix Z690-E Gaming WiFi
        **CPU:** Intel Core i7-12700K
        **RAM:** 32GB DDR4-3200
        **GPU:** NVIDIA GeForce RTX 3080
        **RAID Controller:** LSI MegaRAID 9260-8i
        **Network Cards:** Intel X550-T2 (10GbE)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: 🎯 Expected vs Actual Detection
      description: "What hardware monitoring do you expect vs what you actually see?"
      placeholder: |
        **Expected to see in Home Assistant:**
        - CPU temperature sensor
        - GPU temperature sensor
        - Case fan speed sensors
        
        **Actually detected:**
        - Basic CPU information only
        - No temperature sensors
        - No fan monitoring
        
        **Missing entities that should exist:**
        - sensor.unraid_cpu_temperature
        - sensor.unraid_gpu_temperature
      render: markdown
    validations:
      required: true

  - type: textarea
    id: unraid_webui_data
    attributes:
      label: 🖥️ Unraid Web UI Data
      description: |
        Does this hardware data appear in Unraid's web interface?
        
        Check Dashboard → System and Settings → System Information for sensor data.
      placeholder: |
        **Visible in Unraid Web UI:**
        - CPU temperature: Yes, shows 45°C on Dashboard
        - GPU temperature: No, not shown
        - Fan speeds: Yes, shows 6 fans in System Information
        
        **Screenshots:** (optional - attach or describe)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: graphql_check
    attributes:
      label: 🔍 GraphQL API Data (Optional)
      description: |
        If you're comfortable, check if the data is available in Unraid's GraphQL API.
        
        Go to `https://your-unraid/graphql` in your browser and try querying relevant fields.
        
        Example query:
        ```graphql
        query {
          info {
            cpu { packages { temp } }
          }
          metrics {
            cpu { percentTotal }
          }
        }
        ```
      placeholder: |
        **GraphQL Query Result:**
        ```json
        {
          "info": {
            "cpu": {
              "packages": { "temp": [45.2] }
            }
          }
        }
        ```
        
        Or: "I don't know how to check this"
      render: markdown
    validations:
      required: false

  - type: textarea
    id: integration_logs
    attributes:
      label: 📋 Integration Debug Logs
      description: |
        Enable debug logging for the integration and include relevant logs:

        ```yaml
        logger:
          logs:
            custom_components.unraid: debug
        ```

        Look specifically for messages during integration startup.
      placeholder: |
        ```
        2025-12-27 10:30:00 DEBUG (MainThread) [custom_components.unraid.coordinator] Fetched system data...
        2025-12-27 10:30:01 DEBUG (MainThread) [custom_components.unraid.sensor] Creating CPU temperature sensor...
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Additional Context
      description: "Any other relevant information about your hardware setup"
      placeholder: |
        - Custom cooling solutions or fan controllers
        - BIOS/UEFI settings that might affect hardware detection
        - Previous working configurations or changes made
        - Any custom drivers or plugins installed on Unraid
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: data_collection_willingness
    attributes:
      label: 🤝 Data Collection & Testing Willingness
      description: "How can you help us improve hardware detection for your setup?"
      options:
        - label: "I'm willing to run additional diagnostic commands if needed"
        - label: "I can test development versions of the integration"
        - label: "I can help document the solution for other users with similar hardware"

  - type: checkboxes
    id: troubleshooting_completed
    attributes:
      label: ✅ Checklist
      description: "Please confirm you have done the following:"
      options:
        - label: "I have searched existing [open](https://github.com/ruaan-deysel/ha-unraid/issues) and [closed](https://github.com/ruaan-deysel/ha-unraid/issues?q=is%3Aissue+is%3Aclosed) issues to ensure this isn't a duplicate"
          required: true
        - label: "I am running Unraid 7.2.0 or later (required for GraphQL API)"
          required: true
        - label: "I have verified the integration is working correctly for other features"
          required: true
        - label: "I have checked that the missing hardware data appears in Unraid's web UI"
          required: false

  - type: markdown
    attributes:
      value: |
        ## ⏱️ What Happens Next?

        1. **Analysis**: We'll analyze your hardware information and check if the data is available via GraphQL API
        2. **Research**: We'll investigate if this data can be exposed through the integration
        3. **Development**: If the data is available in the API, we'll work on adding support
        4. **Testing**: You may be asked to test development versions

        **Note**: Some hardware sensors may not be exposed through Unraid's GraphQL API. In those cases, the integration cannot access the data regardless of implementation.

        Thank you for helping improve hardware detection in the Unraid Integration! 🙏
